# load the cleaned data and analyse

Analyze customers by age group, gender, and premium status.
Which group has more customers?

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns   
import numpy as np

cdf=pd.read_csv('cleaned_datasett/customer.csv')
pdf=pd.read_json('cleaned_datasett/product.json')
odf=pd.read_excel('cleaned_datasett/orders.xlsx')

In [22]:
cdf.head(5)

,customer_id,age,gender,occupation,married,registered_date,premium_status,age_category
0,C754,21,Female,Student,1,2023-04-22,0,Teen
1,C854,20,Female,Teacher,1,2019-03-10,0,Teen
2,C132,17,Male,Doctor,1,2019-07-08,0,Children
3,C833,43,Female,Farmer,1,2020-10-09,1,Adult
4,C928,52,Female,Unemployed,1,2017-12-24,0,Adult

In [23]:
cdf['age_category'].value_counts()

age_category
Adult       432
Teen        121
Children     16
Name: count, dtype: int64

In [24]:
cdf['gender'].value_counts()

gender
Female    351
Male      218
Name: count, dtype: int64

In [25]:
cdf['premium_status'].value_counts()

premium_status
1    286
0    283
Name: count, dtype: int64

In [34]:
cdf.groupby(by='premium_status').agg({'premium_status': 'value_counts'})

                premium_status
premium_status
0                          283
1                          286

Show number of orders over time (month-wise or year-wise).
Is the number of orders increasing or decreasing?

In [ ]:
odf['order_date'].dt.year

0      2025
1      2025
2      2025
3      2023
4      2023
       ...
486    2023
487    2023
488    2023
489    2024
490    2023
Name: order_date, Length: 491, dtype: int32

Compare no_of orders  for:

(i)Premium vs non-premium customers

(ii)Male vs female customers

Find total revenue for each sold product category.
Which category gives the highest revenue?

Find average rating for each product category.
Which categories have low ratings?

Identify repeat customers and one-time customers.
How many customers belong to each group?

Calculate percentage of total revenue from repeat customers.
Are repeat customers important for the business?

Analyze premium customer behavior:

(i)How often they place orders

(ii)How much they spend on average

(iii)Which payment mode they use most

Check if high-selling products are frequently out of stock.
Is stock availability affecting sales?

Compare product ratings vs sales.
Do high-rated products sell more than low-rated ones?

Identify products with low sales and low ratings.
Which products should be discontinued from a business point of view?

Based on customer behavior, identify top 3 customer segments the business should focus on.

Based on sales, ratings, and stock:

(i)Which products should be promoted?

(ii)Which products should be discounted?

(iii)Which products should be discontinued?

Find total spending of premium and non-premium customers

Find total sales for available vs not available products.

Find which customer type is buying products with low ratings and suggest one business improvement.

In [26]:
odf.head(5)

,order_id,customer_id,product_id,order_date,net_quantity,payment_mode,amount_saved,actual_amount,amount_to_be_paid
0,O5000,C415,P1076,2025-01-06,4,Credit Card,-3060,4800,4080
1,O5001,C534,P1012,2025-09-03,5,cash,-4588,6750,5735
2,O5002,C291,P1069,2025-04-09,4,Credit Card,-300,400,400
3,O5003,C650,P1090,2023-05-21,5,cash,-1400,6750,1750
4,O5004,C856,P1019,2023-07-05,5,Debit Card,-5400,6750,6750

In [27]:
df1=pd.merge(cdf[['customer_id','premium_status']],odf[['customer_id','payment_mode','amount_to_be_paid']], on='customer_id',how='inner')

In [28]:
Premium_df=df1.loc[df1['premium_status']==1,['customer_id','payment_mode','amount_to_be_paid']]
Premium_df

    customer_id payment_mode  amount_to_be_paid
4          C649  Credit Card              -1804
5          C649         cash                 85
6          C649          UPI               3240
7          C691   Debit Card               1864
8          C975   Debit Card               2745
..          ...          ...                ...
476        C752  Credit Card                100
479        C121         cash               4080
480        C734  Net Banking               1200
485        C533  Net Banking               3354
488        C425         cash                300

[253 rows x 3 columns]

In [29]:
Premium_df['customer_id'].value_counts()

customer_id
C601    6
C494    4
C254    4
C240    4
C978    4
       ..
C752    1
C121    1
C734    1
C533    1
C425    1
Name: count, Length: 161, dtype: int64

In [30]:
Premium_df['amount_to_be_paid'].mean()

np.float64(1937.7549407114625)

In [31]:
Premium_df['payment_mode'].mode()

0    Credit Card
1     Debit Card
Name: payment_mode, dtype: object

In [32]:
Premium_df['payment_mode'].unique()

array(['Credit Card', 'cash', 'UPI', 'Debit Card', 'Net Banking'],
      dtype=object)